hibernate-properties:
  connection.driver_class: org.h2.Driver
  hibernate.connection.username: $(db_user)
  hibernate.connection.password: $(db_password)
  hibernate.connection.url: jdbc:h2:tcp://localhost:9094/./app-data/emdb
  hibernate.dialect: org.hibernate.dialect.H2Dialect

system-properties:
  log4j.configurationFile: log4j2.xml
  app-data.dir: ./app-data
  application.version: 1.1-SNAPSHOT
  service.name: "Rendezvous"
  

http-server:
  http_port: 8040
  https_port: 8041
  http_schemes:
  - http
  - https
  http_timeout: 20000
  keystore: 
    path: ssl.p12
    store-type: PKCS12
    password: $(encrypt_password)
    alias: ssl
  auth:
    method: DIGEST
    role: api
    user_name: apiUser
    user_password: $(api_password)
  subject_names:
    - DNS:localhost
    - IP:127.0.0.1


manufacturer:
   keystore: 
     path: manufacturer.p12
     store-type: PKCS12
     password: $(encrypt_password)


#cbor Web Token (cwt) used for to0 and to1 sessions
cwt:
   keystore: 
     path: ctw.p12
     store-type: PKCS12
     password: $(encrypt_password)


epid:
  # WARNING: do not set testmode to true in production environments
  # if testmode is true, EPID signature verification will only
  # fail for non-signature issues (i.e. malformed requests)
  testMode: false
  # TBD: the url below is the used for production purposes
  # url: http://verify.epid-sbx.trustedservices.intel.com
  # the url below is used for testing purposes only
  url: http://verify.epid-sbx.trustedservices.intel.com

h2-database:
   tcp-server:
     - "-webPort"
     - "9094"
   web-server:
      # - "-webAllowOthers"
      # - "-webExternalNames"
      # - "serverfqdn"
      - "-ifNotExists"
      - "-webPort"
      - "8084" 
workers:
  - org.fidoalliance.fdo.protocol.StandardLogProvider
  - org.fidoalliance.fdo.protocol.StandardMessageDispatcher
  - org.fidoalliance.fdo.protocol.StandardCryptoService
  - org.fidoalliance.fdo.protocol.StandardHttpServer
  - org.fidoalliance.fdo.protocol.StandardDatabaseServer
  - org.fidoalliance.fdo.protocol.StandardCwtKeySupplier
  - org.fidoalliance.fdo.protocol.db.StandardKeyStoreInputStream
  - org.fidoalliance.fdo.protocol.db.StandardKeyStoreOutputStream
  - org.fidoalliance.fdo.protocol.db.StandardValidityDaysSupplier
  - org.fidoalliance.fdo.protocol.db.StandardRvBlobQueryFunction
  - org.fidoalliance.fdo.protocol.db.StandardRvBlobStorageFunction




